#!/usr/bin/env node
// Render the real production UI with illustrative data, without accessing a browser profile.
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
const build=resolve('.output/firefox-mv2');
const html=await readFile(resolve(build,'dashboard.html'),'utf8');
const now=Date.now();
const samples=[['Project notes — Launch checklist','notion.so',false,'timed',2],['Inbox — Team conversations','mail.google.com',false,'awake',5],['Design systems — A practical guide','figma.com',true,'timed',38],['Web platform documentation','developer.mozilla.org',true,'timed',26],['Writing a calmer workday','read.cv',true,'timed',47],['A soundtrack for deep work','open.spotify.com',false,'timed',8]];
function snapshot(theme){return {settings:{globalIdleMinutes:15,theme,siteRules:{'mail.google.com':{mode:'awake'},'web.whatsapp.com':{mode:'awake'},'figma.com':{mode:'timed',minutes:30}}},tabs:samples.map(([title,hostname,discarded,policyMode,idleMinutes],i)=>({id:i+1,windowId:1,url:`https://${hostname}/`,title,hostname,active:i===0,pinned:false,audible:i===5,discarded,lastActiveAt:now-i*60000,idleMinutes,policyMode,timerMinutes:policyMode==='awake'?null:hostname==='figma.com'?30:15,safety:{editing:false,media:i===5},usageTodayMs:0,usageWeekMs:0,favIconUrl:`/favicon/${i}`})),activity:[],stats:{scanCount:12,lastScanAt:now,lastScanDurationMs:2,trackedTabs:6,storageBytes:4096},shortcut:'Ctrl+Shift+U'};}
const colors=['#e1bb62','#d97770','#a5a3f2','#6ba9ca','#b2bd8c','#70bca1'];
const icons=['N','M','F','D','R','♫'];
createServer(async(req,res)=>{try{
const url=new URL(req.url,'http://localhost');const dark=url.searchParams.get('theme')==='dark';const theme=dark?'dark':'light';
if(url.pathname==='/'){
const rules=url.searchParams.get('section')==='rules';
res.setHeader('content-type','text/html; charset=utf-8');res.end(`<!doctype html><html><head><style>@font-face{font-family:Rubik;src:url('/fonts/rubik.woff2')}*{box-sizing:border-box}body{margin:0;width:1600px;height:1280px;font-family:Rubik,sans-serif;color:${dark?'#edf0ff':'#242c40'};background:${dark?'radial-gradient(ellipse at 75% 0%,#283655,#141b2a 70%)':'radial-gradient(ellipse at 75% 0%,#e4eafa,#f2f4f9 70%)'}}header{padding:58px 80px 34px;display:flex;justify-content:space-between;align-items:end}.label{font-size:11px;letter-spacing:2px;color:${dark?'#a4b3ce':'#65748c'};margin-bottom:17px}h1{font-weight:500;font-size:46px;letter-spacing:-2px;margin:0 0 12px}p{font-size:16px;color:${dark?'#a4b3ce':'#65748c'};margin:0}.tag{font-size:10px;letter-spacing:1px;border:1px solid ${dark?'#40516d':'#c7cfdf'};border-radius:30px;padding:12px 20px}.frame{margin:0 80px;border-radius:16px;overflow:hidden;border:1px solid ${dark?'#3a465f':'#c7cfdf'};box-shadow:0 28px 70px ${dark?'#0005':'#203a6420'};background:${dark?'#1b1e24':'white'}}.chrome{height:34px;display:flex;align-items:center;padding:0 18px;gap:6px;border-bottom:1px solid ${dark?'#303540':'#e1e5ee'};color:${dark?'#a4b3ce':'#65748c'};font-size:10px}.dot{width:7px;height:7px;border-radius:50%;background:${dark?'#526079':'#c1c9d8'}}.chrome span:last-child{margin-left:12px;letter-spacing:.8px}iframe{width:1438px;height:960px;border:0;display:block}.foot{display:flex;justify-content:space-between;margin:25px 82px 0;font-size:10px;letter-spacing:1px;color:${dark?'#8798b4':'#73829b'}}</style></head><body><header><div><div class="label">UNLOADER / ${rules?'WEBSITE RULES':'TAB MANAGEMENT'}</div><h1>${rules?'Keep the important things awake.':'Your tabs. A little lighter.'}</h1><p>${rules?'One default timer. A personal rule for every website.':'Let quiet pages rest, without losing your place.'}</p></div><div class="tag">${theme.toUpperCase()} APPEARANCE · LOCAL FIRST</div></header><div class="frame"><div class="chrome"><span class="dot"></span><span class="dot"></span><span class="dot"></span><span>Unloader · ${rules?'Website rules':'Dashboard'}</span></div><iframe src="/dashboard.html?theme=${theme}${rules?'#rules':''}" title="Unloader preview"></iframe></div><div class="foot"><span>REAL INTERFACE / ILLUSTRATIVE DEMO DATA</span><span>ZEN · FIREFOX · CHROME · BRAVE</span></div></body></html>`);
}else if(url.pathname==='/dashboard.html'){
const shim=`<script>const event={addListener(){},removeListener(){}};window.browser={runtime:{id:'unloader-preview',sendMessage:async()=>({ok:true,data:${JSON.stringify(snapshot(theme))}})},tabs:{onCreated:event,onRemoved:event,onUpdated:event,onActivated:event},windows:{onFocusChanged:event}};</script>`;
res.setHeader('content-type','text/html; charset=utf-8');res.end(html.replace('<head>',`<head>${shim}`));
}else if(url.pathname.startsWith('/favicon/')){
const i=Number(url.pathname.split('/').pop());res.setHeader('content-type','image/svg+xml');res.end(`<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"><rect width="32" height="32" rx="8" fill="${colors[i]}"/><text x="16" y="22" text-anchor="middle" font-family="sans-serif" font-weight="bold" font-size="19" fill="#253047">${icons[i]}</text></svg>`);
}else{
const font=url.pathname==='/fonts/rubik.woff2';const file=font?resolve('src/ui/assets/Rubik.woff2'):resolve(build,'.'+url.pathname);if(!font&&!file.startsWith(build+'/'))throw Error('Invalid path');
res.setHeader('content-type',({'.js':'text/javascript','.css':'text/css','.woff2':'font/woff2','.png':'image/png'})[extname(file)]||'application/octet-stream');res.end(await readFile(file));
}
}catch{res.statusCode=404;res.end('Not found');}}).listen(4319,'127.0.0.1',()=>process.stdout.write('README previews: http://127.0.0.1:4319\n'));
