import type { Metadata } from 'next';
import Link from 'next/link';
import { addonUrl } from '../addon';
export const metadata: Metadata = { title: 'Documentation' };
const sections = [['start','Get started'],['memory','Memory estimates'],['rules','Website rules'],['safety','Protected tabs'],['shortcuts','Shortcuts'],['data','Your data'],['troubleshooting','Troubleshooting']];
export default function Docs() { return <div className="docs-layout"><aside><span className="eyebrow">THE FIELD GUIDE</span><h2>Documentation</h2><nav aria-label="Documentation sections">{sections.map(([id,label]) => <a key={id} href={`#${id}`}>{label}</a>)}</nav><Link href="/download" className="text-link">Download Unloader ↗</Link></aside><article className="prose"><div className="eyebrow">UNLOADER / DOCUMENTATION</div><h1>A quieter browser.<br/><em>Here’s how.</em></h1><p className="lead">Keep the pages you want. Let the ones you are not using rest.</p>
<section id="start"><h2>Get started</h2><ol><li><a href={addonUrl}>Install from Firefox Add-ons</a>, or use the <Link href="/download">Chromium download</Link>.</li><li>Click the toolbar icon, then <strong>Manage tabs</strong>.</li><li>Fresh installs automatically unload eligible tabs after 15 minutes. Change this under Rules.</li></ol><p>The dashboard does not need to remain open.</p></section>
<section id="memory"><h2>Memory estimates</h2><p>Browsers do not give extensions reliable live per-tab RAM readings. Unloader reports transparent estimates, not hardware measurements. It matches each hostname against a bundled catalog of more than 500 common sites and uses a documented fallback for unknown sites.</p><p><strong>Estimated freed now</strong> totals tabs currently discarded. <strong>Released across unloads</strong> is a cumulative event total—not memory simultaneously available. A seven-day chart groups successful unloads by local day.</p><p>The editable catalog is <code>extension/src/data/site-memory-estimates.json</code>. Entries contain a domain, name, category, estimated MiB and confidence. Exact domains match before parent domains.</p></section>
<section id="rules"><h2>Website rules</h2><p>Rules apply to exact hostnames such as <code>web.whatsapp.com</code>. Keep awake prevents automatic unloading, Timed sets a custom 1–1,440 minute delay, and Manual waits for your explicit action.</p></section>
<section id="safety"><h2>Protected tabs</h2><p>Automation skips active, pinned, audible, editing, media-playing and loading tabs, plus pages without safety signals. Private, browser and extension pages are excluded. Safety checks are best effort; use Keep awake for work you cannot risk reloading.</p></section>
<section id="shortcuts"><h2>Manual unloading and shortcuts</h2><p>Use the row action or the suggested <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>U</kbd> shortcut (<kbd>⌘</kbd> + <kbd>Shift</kbd> + <kbd>U</kbd> on macOS). Browsers own shortcut assignment. Settings shows the registered key and opens the native shortcut manager where supported.</p></section>
<section id="data"><h2>Your data</h2><p>Rules, activity, estimates and focused-tab usage stay in local extension storage. Settings export/import covers preferences; operational RAM history is intentionally not imported as configuration.</p><Link href="/privacy">Read the privacy policy ↗</Link></section>
<section id="troubleshooting"><h2>Troubleshooting</h2><p>If a tab will not unload, check its protection reason and rule. If the shortcut does not respond, use Customize shortcut in Settings. Temporary Firefox add-ons disappear after restart; install the signed listing for daily use.</p><p><a href="https://github.com/wrestle-R/Unloader/issues">Report a problem on GitHub</a> without sharing private tab URLs.</p></section>
</article></div>; }
